#ifndef ATHREAD_OFFSETS_H__
#define ATHREAD_OFFSETS_H__

; Auto-generated. Do not edit by hand.
; Generated by tools/gen_athread_offsets.c

.equ ATHREAD_SIZE, 12
.equ ATHREAD_SP_OFFSET, 2
.equ ATHREAD_STACK_HIGH_OFFSET, 6
.equ ATHREAD_STATE_OFFSET, 9
.equ ATHREAD_STARTED_OFFSET, 10

.equ TS_READY, 1
.equ TS_RUNNING, 2

#endif // ATHREAD_OFFSETS_H__
