#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "athread.h"

#if defined(__AVR__)
typedef athread_t athread_layout_t;
#else
typedef struct __attribute__((aligned(2))) {
    uint8_t entry[2];
    uint16_t sp;
    uint16_t stack_low;
    uint16_t stack_high;
    uint8_t tid;
    uint8_t state;
    uint8_t started;
} athread_layout_t;
#endif

static int write_offsets(const char *out_path) {
    FILE *out = fopen(out_path, "w");
    if (!out) {
        return 1;
    }

    fprintf(out, "#ifndef ATHREAD_OFFSETS_H__\n");
    fprintf(out, "#define ATHREAD_OFFSETS_H__\n\n");
    fprintf(out, "; Auto-generated. Do not edit by hand.\n");
    fprintf(out, "; Generated by tools/gen_athread_offsets.c\n\n");

    fprintf(out, ".equ ATHREAD_SIZE, %u\n", (unsigned)sizeof(athread_layout_t));
    fprintf(out, ".equ ATHREAD_SP_OFFSET, %u\n", (unsigned)offsetof(athread_layout_t, sp));
    fprintf(out, ".equ ATHREAD_STACK_HIGH_OFFSET, %u\n", (unsigned)offsetof(athread_layout_t, stack_high));
    fprintf(out, ".equ ATHREAD_STATE_OFFSET, %u\n", (unsigned)offsetof(athread_layout_t, state));
    fprintf(out, ".equ ATHREAD_STARTED_OFFSET, %u\n\n", (unsigned)offsetof(athread_layout_t, started));

    fprintf(out, ".equ TS_READY, %u\n", (unsigned)TS_READY);
    fprintf(out, ".equ TS_RUNNING, %u\n\n", (unsigned)TS_RUNNING);

    fprintf(out, "#endif // ATHREAD_OFFSETS_H__\n");

    fclose(out);
    return 0;
}

int main(void) {
    const char *out_path = "include/athread_offsets.h";
    return write_offsets(out_path);
}
